version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  slack: circleci/slack@4.1.1
workflows:
  Compliar y ejecutar Test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
        command: '-X verify'
  send-notification:
    jobs:
      - notify:
          context: slack-secrets


