#version: 2.1
#orbs:
#  slack: circleci/slack@3.4.0
#  maven: circleci/maven@1.0.3
#
#jobs:
#  build:
#    docker:
#      - image: circleci/openjdk:8-jdk-node
#    steps:
#      - checkout
##      - maven/test
#      - run:
#          name: install maven and execute
#          command: |
#            mvn install
#            mvn verify
#            echo 'agregando el reporte generado por serenity'
#            mvn serenity:aggregate
##      - run:
##          name: hello Word
##          command: |
##            echo 'Hello World!'
##            echo 'finaliza las primeras compilaciones'
##      - run:
##          name: probando el orbe de maven
##          command: |
##            echo 'ejecutando el orbs de maven'
#      - store_test_results:
#          path: ~/test-results
#      - store_artifacts:
#          path: ~/test-results/junit
#      - persist_to_workspace:
#         root: .
#         paths:
#           - AutomationServices-CircleCi/target
######################
#workflows:          #
#  maven_test:       #
#    jobs:           #
#      - maven/test  #
######################


#version: 2.1
#orbs:
#  slack: circleci/slack@3.4.0
#  maven: circleci/maven@1.0.3
#
#jobs:
#  build:
#    docker:
#      - image: circleci/openjdk:8-jdk-node
#    steps:
#      - checkout
#      - run: echo "this is the build job"
#  test:
#    docker:
#      - image: circleci/openjdk:8-jdk-node
#    steps:
#      - checkout
#      - run: echo "this is the test job"
#
#  automation:
#    docker:
#      - image: circleci/openjdk:8-jdk-node
#    steps:
#      - slack/notify:
#          channel: chillout
#          color: '#42e2f4'
#          mentions: 'here'
#          message: El pipeline fue ejecutado
#          webhook: ${SLACK_WEBHOOK_AUTOMATION}

version: 2.1
orbs:
  maven: circleci/maven@1.0.3
  slack: circleci/slack@3.4.2
jobs:
  build-test-and-notify:
    executor:
      name: compilar ejecutar y notificar
    steps:
      - checkout
      - run:
          name: maven verify
          command: mvn verify
      - run: mvn clean verify
      - slack/notify:
          color: "#42e2f4"
          mentions: 'here'
          message: A custom message to notify the channel about the latest build
      - slack/status:
          fail_only: false
          mentions: 'here'
workflows:
  build-and-notify:
    jobs:
      - build-test-and-notify