version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  slack: circleci/slack@4.1.1
jobs:
  build_and_test:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - run:
          name: maven completa
          command: |
            mvn --version
            mvn clean verify
