version: 2.1
orbs:
  slack: circleci/slack@3.4.0
  maven: circleci/maven@1.0.3

jobs:
  build and test:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - run:
          name: install maven and execute
          command: |
            mvn install
            mvn verify

  test orb maven:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - slack/notify:
          color: '#42e2f4'
          mentions: 'USERID1,USERID2,'
          message: This is a custom message notification
          webhook: webhook