version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  slack: circleci/slack@4.1.1

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - slack/notify:
          color: '#42e2f4'
          mentions: 'USERID1,USERID2,'
          message: This is a custom message notification
          webhook: webhook