version: 2.1
orbs:
  slack: circleci/slack@3.4.0
  maven: circleci/maven@1.0.3

jobs:
  build_test_norify:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
#      - maven/test
      - run:
          name: install maven and execute
          command: |
            mvn install
            mvn verify
            echo 'agregando el reporte generado por serenity'
            mvn serenity:aggregate
      - run:
          name: hello Word
          command: |
            echo 'Hello World!'
            echo 'finaliza las primeras compilaciones'
      - run:
          name: probando el orbe de maven
          command: |
            echo 'ejecutando el orbs de maven'
      - slack/notify:
          color: "#42e2f4"
          mentions: 'here'
          message: finalizo la ejecucion de la integracion continua

workflows:
  build_test_norify:
    jobs:
      - build_test_norify
      - maven/test

#  automation_notification_qa:
#    docker:
#      - image: circleci/openjdk:8-jdk-node
#    steps:
#      - slack/notify:
#          channel: chillout
#          color: '#42e2f4'
#          mentions: 'here'
#          message: Do you want to see the automatic report scheduled in QA env? go to https://e2e-testing-reports.s3.amazonaws.com/be/qa/<< pipeline.id >>/site/serenity/index.html
#          webhook: ${SLACK_WEBHOOK_AUTOMATION}

######################
#workflows:          #
#  maven_test:       #
#    jobs:           #
#      - maven/test  #
######################


#version: 2.1
#orbs:
#  slack: circleci/slack@3.4.0
#  maven: circleci/maven@1.0.3
#
#jobs:
#  build:
#    docker:
#      - image: circleci/openjdk:8-jdk-node
#    steps:
#      - checkout
#      - run: echo "this is the build job"
#  test:
#    docker:
#      - image: circleci/openjdk:8-jdk-node
#    steps:
#      - checkout
#      - run: echo "this is the test job"
#
#  automation:
#    docker:
#      - image: circleci/openjdk:8-jdk-node
#    steps:
#      - slack/notify:
#          channel: chillout
#          color: '#42e2f4'
#          mentions: 'here'
#          message: El pipeline fue ejecutado
#          webhook: ${SLACK_WEBHOOK_AUTOMATION}
