version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - run: mvn install
      - run: mvn verify
      - slack/notify:
          color: '#42e2f4'
          message: Mensaje llega a Slack
          webhook: webhook
orbs:
  slack: circleci/slack@4.1.1
workflows:
  your-workflow:
    jobs:
      - build