version: 2.1
orbs:
  slack: circleci/slack@3.4.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - run:
          name: install maven and execute
          command: |
            mvn install
            mvn verify
            echo mensaje

  automation_notify:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - slack/notify:
          channel: chillout
          color: '#42e2f4'
          mentions: 'here'
          message: mensaje de la anotificacion de circleci
          webhook: https://hooks.slack.com/services/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