version: 2.1
orbs:
  slack: circleci/slack@3.4.0

jobs:
  build and test:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - run:
          name: install maven and execute
          command: |
            mvn install
            mvn verify

  test orb maven:
    docker:
      - image: circleci/openjdk:8-jdk-node
    orbs:
      maven: circleci/maven@1.0.3
    version: 2.1
    workflows:
      maven_test:
        jobs:
          - maven/test