version: 2.1
orbs:
  slack: circleci/slack@3.4.0
  maven: circleci/maven@1.0.3

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - maven/test
      - run:
          name: install maven and execute
          command: |
            mvn install
            mvn verify
            echo mensaje
      - run:
          name: hello Word
          command: |
            echo 'Hello World!'
            echo 'finaliza las primeras compilaciones'
      - run:
          name: probando el orbe de maven
          command: |
            echo 'ejecutando el orbs de maven'

######################
#workflows:          #
#  maven_test:       #
#    jobs:           #
#      - maven/test  #
######################