version: 2.1
orbs:
  slack: circleci/slack@3.4.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - run:
          name: install maven and execute
          command: |
            mvn install
            mvn verify